//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.09 at 11:10:51 AM ACDT 
//


package schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attribute",
    "boundary",
    "vehicleStatus",
    "apolloLandingSite",
    "roverLandingSite",
    "trackToColor",
    "obstacle",
    "zone",
    "track"
})
@XmlRootElement(name = "lunarrovermap")
public class Lunarrovermap {

    @XmlAttribute(name = "units")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String units;
    protected List<Attribute> attribute;
    @XmlElement(required = true)
    protected Boundary boundary;
    @XmlElement(name = "vehicle-status", required = true)
    protected VehicleStatus vehicleStatus;
    @XmlElement(name = "apollo-landing-site", required = true)
    protected ApolloLandingSite apolloLandingSite;
    @XmlElement(name = "rover-landing-site", required = true)
    protected RoverLandingSite roverLandingSite;
    @XmlElement(name = "track-to-color", required = true)
    protected TrackToColor trackToColor;
    protected List<Obstacle> obstacle;
    protected List<Zone> zone;
    protected List<Track> track;

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        if (units == null) {
            return "metres";
        } else {
            return units;
        }
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    public List<Attribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<Attribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the boundary property.
     * 
     * @return
     *     possible object is
     *     {@link Boundary }
     *     
     */
    public Boundary getBoundary() {
        return boundary;
    }

    /**
     * Sets the value of the boundary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boundary }
     *     
     */
    public void setBoundary(Boundary value) {
        this.boundary = value;
    }

    /**
     * Gets the value of the vehicleStatus property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleStatus }
     *     
     */
    public VehicleStatus getVehicleStatus() {
        return vehicleStatus;
    }

    /**
     * Sets the value of the vehicleStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleStatus }
     *     
     */
    public void setVehicleStatus(VehicleStatus value) {
        this.vehicleStatus = value;
    }

    /**
     * Gets the value of the apolloLandingSite property.
     * 
     * @return
     *     possible object is
     *     {@link ApolloLandingSite }
     *     
     */
    public ApolloLandingSite getApolloLandingSite() {
        return apolloLandingSite;
    }

    /**
     * Sets the value of the apolloLandingSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApolloLandingSite }
     *     
     */
    public void setApolloLandingSite(ApolloLandingSite value) {
        this.apolloLandingSite = value;
    }

    /**
     * Gets the value of the roverLandingSite property.
     * 
     * @return
     *     possible object is
     *     {@link RoverLandingSite }
     *     
     */
    public RoverLandingSite getRoverLandingSite() {
        return roverLandingSite;
    }

    /**
     * Sets the value of the roverLandingSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoverLandingSite }
     *     
     */
    public void setRoverLandingSite(RoverLandingSite value) {
        this.roverLandingSite = value;
    }

    /**
     * Gets the value of the trackToColor property.
     * 
     * @return
     *     possible object is
     *     {@link TrackToColor }
     *     
     */
    public TrackToColor getTrackToColor() {
        return trackToColor;
    }

    /**
     * Sets the value of the trackToColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackToColor }
     *     
     */
    public void setTrackToColor(TrackToColor value) {
        this.trackToColor = value;
    }

    /**
     * Gets the value of the obstacle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obstacle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObstacle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Obstacle }
     * 
     * 
     */
    public List<Obstacle> getObstacle() {
        if (obstacle == null) {
            obstacle = new ArrayList<Obstacle>();
        }
        return this.obstacle;
    }

    /**
     * Gets the value of the zone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Zone }
     * 
     * 
     */
    public List<Zone> getZone() {
        if (zone == null) {
            zone = new ArrayList<Zone>();
        }
        return this.zone;
    }

    /**
     * Gets the value of the track property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the track property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Track }
     * 
     * 
     */
    public List<Track> getTrack() {
        if (track == null) {
            track = new ArrayList<Track>();
        }
        return this.track;
    }

}
